In [1]:
print("hello")

hello


In [18]:
import pandas as pd
import numpy as np 
from sklearn import linear_model
import math 

In [19]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [20]:
#Filling missing values 
median_bedrooms = df.bedrooms.median()
median_bedrooms

4.0

In [21]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [22]:
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [25]:
lm = linear_model.LinearRegression()
lm.fit(df[["area", "bedrooms", "age"]], df.price)

LinearRegression()

In [27]:
lm.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [28]:
lm.intercept_

221323.0018654043

In [29]:
lm.predict([[3000, 3, 40]])

C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [30]:
df2 = pd.read_csv("hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [31]:
from word2number import w2n

In [34]:
df2.experience = df2.experience.fillna("zero")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df2.experience = df2.experience.apply(lambda x: w2n.word_to_num(x))
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [39]:
test_score_mean = math.floor(df2["test_score(out of 10)"].mean())
test_score_mean

7

In [40]:
df2["test_score(out of 10)"] = df2["test_score(out of 10)"].fillna(test_score_mean)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [42]:
lm = linear_model.LinearRegression()
lm.fit(df2[["experience","test_score(out of 10)","interview_score(out of 10)"]],
       df2["salary($)"])

LinearRegression()

In [43]:
lm.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [44]:
lm.intercept_

14992.65144669314

In [45]:
lm.predict([[9,10,8]])

C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([80686.02410871])